defaults:
  - base

hydra:
  searchpath:
    - pkg://verl.trainer.config

trainer:
  experiment_name: frozenlake-main


es_manager:
  train:
    env_configs:
      tags: ["CoordFrozenLake"]
  val:
    env_configs:
      tags: ["CoordFrozenLake"]
